name: Build unsigned IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'   # Укажите версию под ваши нужды

      - name: Build archive
        run: |
          xcodebuild archive \
            -project OneDay.xcodeproj \
            -scheme "OneDay" \
            -configuration Release \
            -archivePath "$GITHUB_WORKSPACE/build/OneDay.xcarchive" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO

      - name: Export unsigned IPA
        run: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>teamID</key>
            <string></string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$GITHUB_WORKSPACE/build/OneDay.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$GITHUB_WORKSPACE/build/ipa" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO
